@startuml 旅游申请业务流程活动图
start

:顾客到店咨询;

fork
  :前台员工查询旅游团信息;
  :显示可选旅游团列表;
end fork

:选择旅游团;

if (是否满足申请条件？) then (是)
  :录入申请责任人信息;
  :录入大人和小孩人数;

  partition "订金处理" {
    :计算订金金额;
    :收取订金;
    :记录订金支付;
    :提供订金收据;
    :提供旅游申请书;
  }

  :顾客填写申请书并邮寄回旅行社;

  partition "参加者信息录入" {
    :接收邮寄的申请书;
    :查询申请记录;
    :录入参加者信息;
    :申请完成;
  }

  partition "确认与催款" {
    :打印旅游确认书;
    :打印余额交款单;
    :邮寄给申请责任人;
  }

  :顾客支付余款;

  if (是否在支付期限内？) then (是)
    :记录余款支付;
    :申请完成，等待出发;
  else (否)
    :告知已过支付期限;
  endif

else (否)
  :告知顾客无法申请的原因;
  :结束咨询;
endif

partition "后续业务（可选）" {
  if (是否需要变更？) then (是)
    if (变更类型？) then (参加者信息变更)
      :修改参加者信息;
      if (变更为申请责任人？) then (是)
        :指定新申请责任人;
      else (否)
      endif
    else (取消参加者)
      :取消参加者;
      if (取消申请责任人？) then (是)
        :指定新申请责任人;
      else (否)
      endif
    endif
  else (取消整个申请)
    :计算取消手续费;
    :扣除手续费;
    :退还余款;
  endif
}

stop

@enduml
